// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-ObVBfH5h7viC4mE5WuLr7YujJ_Y6nhI',
    appId: '1:186598138943:web:70d23fdfc783a8c08cc48a',
    messagingSenderId: '186598138943',
    projectId: 'rahmatproject-firebase',
    authDomain: 'rahmatproject-firebase.firebaseapp.com',
    storageBucket: 'rahmatproject-firebase.firebasestorage.app',
    measurementId: 'G-MH44P4CY2Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHixvpeZ4YRAVfCbBKLcbdRIs28UqyYSE',
    appId: '1:186598138943:android:20dc615f73f0c52f8cc48a',
    messagingSenderId: '186598138943',
    projectId: 'rahmatproject-firebase',
    storageBucket: 'rahmatproject-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgrgqEZFWeQ6dDwG1J3J12gTIyBysxHdM',
    appId: '1:186598138943:ios:36d41381466ca2858cc48a',
    messagingSenderId: '186598138943',
    projectId: 'rahmatproject-firebase',
    storageBucket: 'rahmatproject-firebase.firebasestorage.app',
    iosBundleId: 'com.example.projectFirebaseRahmat',
  );
}
